Feature/dsp 42 create initial user classes and models in account service
Dwit-Tech/account-service pull request #3
Opened 2023-02-07 22:43 UTC by johnny2565

Pushed this code for review

2023-02-08 01:18 UTC, dabensymon requested changes
Good job but the contents of this PR are mostly beyond scope. We do not require the implementations yet. Just the class structures.

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Dtos/UserDto.cs
> +    //iuserrepository => getuser, createuser, modify and create user values should be manipulated
Remove comments that have no purpose

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Dtos/UserCreateDto.cs
> +    public class UserCreateDto:UserDto
Why do you need to structure your DTOs like this?

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Interfaces/IUserService.cs
> +    {
This is beyond scope of your task.

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/UserService.cs
> +            if(user != null)
This is beyond scope of your task.

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/UserService.cs
> +            var readDto = _mapper.Map<User>(user);
This is beyond scope of your task.

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/UserService.cs
> +            var allUser = _userRepository.GetAll();
This is beyond scope of your task.

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/UserService.cs
> +            var foundUser  =  _userRepository.GetUserById(id);
This is beyond scope of your task.

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/UserService.cs
> +            var userUpdateDto = new UserCreateDto
This is beyond scope of your task.

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Data/Entities/User.cs
> +        [Required]
Why is Confirm Password in the entity? Meanwhile no password property in the DTO that needs  it

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Data/Migrations/20230208165756_InitialMigration.cs
> +                    Confirm_Password = table.Column<string>(type: "text", nullable: false),
effect of adding confirm password to your entity

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Data/repository/IUserRepository.cs
> +        IEnumerable<User> GetAll();
This is beyond scope of your task.

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Data/repository/UserRepository.cs
> +        List<User> MockUsers = new List<User>(); //Using this as the database
I like this

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.Data/repository/UserRepository.cs
> +        public User CreateUser(User user)
Again the methods here are beyond scope of your task.

2023-02-08 01:18 UTC, dabensymon commented on src/DwitTech.AccountService.WebApi/Controllers/UserController.cs
> +        public ActionResult GetAllUsers()
This is beyond scope of your task.

2023-02-10 14:42 UTC, dabensymon requested changes

2023-02-10 14:42 UTC, dabensymon commented on src/DwitTech.AccountService.Data/repository/UserRepository.cs
> +        List<User> MockUsers = new List<User>(); //Using this as the database
Is this in use? If not, take it out.

2023-02-10 14:42 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Dtos/UserDto.cs
> +    }
I believe password is missing here

2023-02-10 18:13 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Dtos/UserDto.cs
> +    }
This is still pending

2023-02-12 00:20 UTC, giftedGeorge approved these changes

2023-02-12 00:21 UTC, giftedGeorge approved these changes
Looks good to me

2023-02-12 00:51 UTC, dabensymon approved these changes
LGTM... Please check the actions tag and confirm deployment is succesful

2023-02-12 00:52 UTC, merged