Creating and Implemention Security HashString Method.
Dwit-Tech/account-service pull request #4
Opened 2023-02-08 01:00 UTC by Maryann529

Kindly review my code!

2023-02-08 01:08 UTC, dabensymon requested changes

2023-02-08 01:08 UTC, dabensymon commented on C-Sharp-Tutorial/C-Sharp-Tutorial.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Why is this here? Please remove it.

2023-02-08 01:08 UTC, dabensymon commented on C-Sharp-Tutorial/Program.cs
> +﻿using System;
Same here. What is the purpose of this?

2023-02-08 01:08 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Interfaces/ISecurityRepository.cs
> +﻿using System;
What is this for? doesnt seem to have a purpose

2023-02-08 01:08 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/SecurityService.cs
> +        /*public bool VerifiedHashPasswords(byte hashpassword1, byte hashpassword2)
Do not comment out code. Delete it instead.

2023-02-08 01:08 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/SecurityService.cs
> +    public class SecurityService
This should implement an interface.

2023-02-08 01:08 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/SecurityService.cs
> +            StringBuilder hashedstringoutput = new StringBuilder(hashpassword.Length);
variable and parameter names should be camelCase. All your variables and parameters are guilty of this.

2023-02-10 16:52 UTC, dabensymon reviewed
Not bad. Just fix the few comments lets close it.

2023-02-10 16:52 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/SecurityService.cs
> +        public string HashString(string userPassword)
This method hashes any string, not just password. So it should be clearText or inputString and not userPassword

2023-02-10 16:52 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/SecurityService.cs
> +            string collectedPassword = userPassword;
why are you assigning another variable here?

2023-02-10 16:52 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/SecurityService.cs
> +            byte[] hashPassword;
remove all mention of password from this implementation cos its not just a password thing

2023-02-10 16:52 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/SecurityService.cs
> +            byte[] asciibyte;
camelCase please

2023-02-10 16:52 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/SecurityService.cs
> +            StringBuilder hashedStringOutput = new StringBuilder(hashPassword.Length);
bad naming here again. This should be called something like stringBuilder or outputStringBuilder

2023-02-11 15:18 UTC, dabensymon reviewed
Still pending

2023-02-12 00:09 UTC, giftedGeorge submitted a review, later dismissed
It seems like you haven't made the changes with regards to the comment Ben made about your method variables and arguments. I still see some references to "password" in both the interface and implementation

2023-02-12 01:05 UTC, giftedGeorge reviewed
Looks good to me

2023-02-14 10:37 UTC, dabensymon reviewed
Just 1 issue

2023-02-14 10:37 UTC, dabensymon commented on src/DwitTech.AccountService.Core/Services/SecurityService.cs
> +            /*string collectedPassword = inputString;*/
why is this commented out code still here?

2023-02-14 10:45 UTC, dabensymon approved these changes

2023-02-14 10:45 UTC, merged